### ISSUE TITLE
功能建议

### ISSUE THREAD

**Issue by iibob** [pcloth/translate-speaker#10]
开发者你好，能否添加一个开关，鼠标选中代码时，取消自动翻译
- 当鼠标选中一部分代码后，插件就开始对选中内容自动进行翻译，将结果显示在左下角状态栏上，这很好，能减少想要翻译时的操作
- 但大多数时候都是在复制粘贴代码，或者双击修改某个单词，也会自动翻译，这会产生很多用不到的翻译操作。
- 尝试修改 translateSpeaker.wordMaxLength 这个参数，但自动翻译依旧会进行，翻译内容的长度为设置的参数。
- 或者是否能在 鼠标完成选中代码 这一操作后进行判断，再决定是否翻译

感谢你的插件，对我很有帮助，期待你的回复。

**Comment by pcloth** [comment]
> 开发者你好，能否添加一个开关，鼠标选中代码时，取消自动翻译
> 
> * 当鼠标选中一部分代码后，插件就开始对选中内容自动进行翻译，将结果显示在左下角状态栏上，这很好，能减少想要翻译时的操作
> * 但大多数时候都是在复制粘贴代码，或者双击修改某个单词，也会自动翻译，这会产生很多用不到的翻译操作。
> * 尝试修改 translateSpeaker.wordMaxLength 这个参数，但自动翻译依旧会进行，翻译内容的长度为设置的参数。
> * 或者是否能在 鼠标完成选中代码 这一操作后进行判断，再决定是否翻译
> 
> 感谢你的插件，对我很有帮助，期待你的回复。

有一个参数是：translateSpeaker.mode，如果设置为manual之后，选中文字后，必须使用右键菜单或者快捷键才开始翻译转换

**Comment by iibob** [comment]
感谢，我会了
