### ISSUE TITLE
声音控制有嘛？

### ISSUE THREAD

**Issue by chaseFunny** [pcloth/translate-speaker#11]
我发现现在声音是和我电脑其他播放器声音不太一样，会更小一点，请问如果 我想要将声音调成和正常音量一样呢？

**Comment by pcloth** [comment]
> 我发现现在声音是和我电脑其他播放器声音不太一样，会更小一点，请问如果 我想要将声音调成和正常音量一样呢？

语音播放调用的是系统tts，是一个外部依赖`say.js`提供的，我看它代码中是在windows下调用的powershell中的指令，目前它没有提供音量控制参数。

对方仓库在此：[https://github.com/Marak/say.js](https://github.com/Marak/say.js)
