### ISSUE TITLE
UI建议

### ISSUE THREAD

**Issue by iibob** [pcloth/translate-speaker#12]
开发你好，我很喜欢你的插件，同时满足了我中英互译和变量格式转换，完美。

如果可以的话，可以考虑优化下UI显示，目前的翻译和转换，操作后显示出来的内容过于冗杂。
以至于第一次安装尝试使用时，有点分不清两个快捷键的区别。

![image](https://github.com/pcloth/translate-speaker/assets/10295975/c161319a-dca3-48aa-950f-137d1a721435)

序号 | 原文 | 替换类型 | 译文 | 解释说明

建议仅保留译文和类型即可，或者再加个序号。
原文和说明与现有内容重复了，更改后会更直观。
使用熟练后，其他内容也会被主动忽略。
或者在设置里加个开关，可以 开/关 显示说明等内容。

祝好，望回复。

**Comment by pcloth** [comment]
> 开发你好，我很喜欢你的插件，同时满足了我中英互译和变量格式转换，完美。
> 
> 如果可以的话，可以考虑优化下UI显示，目前的翻译和转换，操作后显示出来的内容过于冗杂。 以至于第一次安装尝试使用时，有点分不清两个快捷键的区别。
> 
> ![image](https://private-user-images.githubusercontent.com/10295975/286439489-c161319a-dca3-48aa-950f-137d1a721435.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjkwNjk4NTUsIm5iZiI6MTcyOTA2OTU1NSwicGF0aCI6Ii8xMDI5NTk3NS8yODY0Mzk0ODktYzE2MTMxOWEtZGNhMy00OGFhLTk1MGYtMTM3ZDFhNzIxNDM1LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMTYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDE2VDA5MDU1NVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTQyZDU1ZGM0YzVhNDVjNjNiMmNmMzNiZmViMTRkY2FlYTg1N2Q2OTEwNjU3NjhlNDY2YTk3MzNkMTlhM2QxNzAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.HqyjtYmHrW5BoR28EeTUzRlMAbmIQGRf51119cnb05w)
> 
> 序号 | 原文 | 替换类型 | 译文 | 解释说明
> 
> 建议仅保留译文和类型即可，或者再加个序号。 原文和说明与现有内容重复了，更改后会更直观。 使用熟练后，其他内容也会被主动忽略。 或者在设置里加个开关，可以 开/关 显示说明等内容。
> 
> 祝好，望回复。

更新了版本到1.7.3，添加了两个参数，用于控制picker的文字内容：
|参数名字|类型|默认值|说明|
|---|---|---|---|
|pickLabelFormat|string|`{num} [ {shortText} ] {midstr}{typeName} => [ {shortOutText} ]`|拾取器的显示格式|
|showPickDesc|boolean|true|是否显示拾取器的描述|

您这个需求，可以把showPickDesc设置为false，然后把pickLabelFormat设置为`[ {shortText} ] {midstr} => [ {shortOutText} ]`

**Comment by iibob** [comment]
@pcloth 感谢 感谢
