### ISSUE TITLE
关于 apiAccount 配置

### ISSUE THREAD

**Issue by tjt740** [pcloth/translate-speaker#13]
关于 apiAccount 配置，作者老师能不能放在明显点的位置，或者加个案例demo， 写的字太少了，分析了半天。
 "translateSpeaker.apiAccount": [
        "baidu=你的appid,你的密码,1", 举个🌰
        "bing=AFC76A66CF4F434ED080D245C30CF1E71C22959C,,1"
    ]

**Comment by tjt740** [comment]
顺带问个问题，怎么设置翻译出来的文本格式呢？{num} [ {shortText} ] {midstr}{typeName} => [ {shortOutText} ] 修改了感觉样式就不对了。我想输出 className[类名称] 这种小驼峰的格式

**Comment by pcloth** [comment]
> 顺带问个问题，怎么设置翻译出来的文本格式呢？{num} [ {shortText} ] {midstr}{typeName} => [ {shortOutText} ] 修改了感觉样式就不对了。我想输出 className[类名称] 这种小驼峰的格式

```
{shortOutText} {typeName}
```

之前出错是一个bug，已经修复了，请升级到1.7.4
