### ISSUE TITLE
追加时会多空格

### ISSUE THREAD

**Issue by toojian** [pcloth/translate-speaker#14]
谢谢你开发的好用插件。我在追加时发现：
1、每个大写字母前都会多出两空格。例如：“the GNU General” 翻译追加后变为了“the   G  N  U   General [ 联合国将军 ]”。
2、原英文中的短横线没有了。例如：“the startup-file.“翻译追加后变成了“the startup file [ 启动文件 ]”
建议追加结果不改变所选原文。

**Comment by pcloth** [comment]
> 谢谢你开发的好用插件。我在追加时发现： 1、每个大写字母前都会多出两空格。例如：“the GNU General” 翻译追加后变为了“the G N U General [ 联合国将军 ]”。 2、原英文中的短横线没有了。例如：“the startup-file.“翻译追加后变成了“the startup file [ 启动文件 ]” 建议追加结果不改变所选原文。

请更新到1.7.5版本以上，并将参数englishNotCodingMode设置为true，因为这个插件的核心功能还是编码时候的变量处理，纯翻译的话请开启这个参数，避免英文被当作变量名来清洗结构。

**Comment by toojian** [comment]
//谢谢你的改进，可惜的是1.7.5对于我的python无法翻译，可能是兼容性问题或是循环太多内存不足。
我参照你以前的修改了一下能顺利运行
// 选中的英文文本清洗干净
function englishClearSelectionText(text) {
&nbsp; &nbsp; if (!text) {
&nbsp; &nbsp; &nbsp; &nbsp; return text;
&nbsp; &nbsp; }
&nbsp; &nbsp; const englishNotCodingMode = getConfigValue('englishNotCodingMode');
&nbsp; &nbsp; if (englishNotCodingMode) {
&nbsp; &nbsp; &nbsp; &nbsp; return text;
&nbsp; &nbsp; }
&nbsp; &nbsp; // 下划线，连接线，小数点自动替换成空格
&nbsp; &nbsp; text = text.replace(/_|-|\./g, ' ');
&nbsp; &nbsp; 
&nbsp; &nbsp; if (/^[A-Z][A-Z0-9]*$/.test(text)) {
&nbsp; &nbsp; &nbsp; &nbsp; // 全大写不处理， ALL A1 
&nbsp; &nbsp; } else {
&nbsp; &nbsp; &nbsp; &nbsp; // 驼峰替换成空格，末尾大写字母串前加空格 &nbsp;abAbCPU AbAbCPU
&nbsp; &nbsp; &nbsp; &nbsp; text = text.replace(/([A-Z][a-z0-9]+|[A-Z]+$)/g, " $1");
&nbsp; &nbsp; &nbsp; &nbsp; //去掉多余空格
&nbsp; &nbsp; &nbsp; &nbsp; text = text.replace(/\s+/g, " ").trim();
&nbsp; &nbsp; }
&nbsp; &nbsp; return text &nbsp;
}




//另外还改了一行，处理全大写
    _convertVariablesToWords(text) {         // 判断命名格式         if (/^[a-z][a-zA-Z0-9]*$/.test(text)) {             // 小驼峰命名格式             return text.replace(/([A-Z])/g, ' $1').toLowerCase();         } else if (/^[A-Z][a-zA-Z0-9]*$/.test(text)) {             // 大驼峰命名格式，连续大写
            //return text.replace(/([A-Z])/g, ' $1').trim().toLowerCase();             return text.replace(/([A-Z][a-z0-9]+|[A-Z]+$)/g, ' $1').trim().toLowerCase();         } else if (/^[a-zA-Z][a-zA-Z0-9_]*$/.test(text)) {             // 下划线（蛇形）命名格式             return text.replace(/_/g, ' ').toLowerCase();         } else if (/^[a-zA-Z][a-zA-Z0-9\-]*$/.test(text)) {             // 短横线命名格式             return text.replace(/-/g, ' ').toLowerCase();         } else {             // 无法识别的格式，返回原始文本             return text;         }     }






完美世界
***@***.***



&nbsp;

**Comment by toojian** [comment]
你以前的逻辑是对的、简洁的，我走了弯路，只需处理驼峰：replace(/([a-z0-9])([A-Z])/g, "$1 $2")
// 选中的英文文本清洗干净
function englishClearSelectionText(text) {
&nbsp; &nbsp; if (!text) {
&nbsp; &nbsp; &nbsp; &nbsp; return text;
&nbsp; &nbsp; }
&nbsp; &nbsp; const englishNotCodingMode = getConfigValue('englishNotCodingMode');
&nbsp; &nbsp; if (!englishNotCodingMode) {
&nbsp; &nbsp; // 下划线，连接线，小数点自动替换成空格
&nbsp; &nbsp; text = text.replace(/_|-|\./g, ' ');
&nbsp; &nbsp; // 驼峰替换成空格 abAbCPU6 AbAbCPU6 ALL ALL1
&nbsp; &nbsp; text = text.replace(/([a-z0-9])([A-Z])/g, "$1 $2");
&nbsp; &nbsp; //去掉多余空格(目前未产生)
&nbsp; &nbsp; //text = text.replace(/\s+/g, " ").trim();
&nbsp; &nbsp; }
&nbsp; &nbsp; return text &nbsp;
}


下面这个也改了大驼峰那一行，不对全大写加空格
&nbsp; &nbsp; _convertVariablesToWords(text) {
&nbsp; &nbsp; &nbsp; &nbsp; // 判断命名格式
&nbsp; &nbsp; &nbsp; &nbsp; if (/^[a-z][a-zA-Z0-9]*$/.test(text)) {
&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; // 小驼峰命名格式
&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; return text.replace(/([A-Z])/g, ' $1').toLowerCase();
&nbsp; &nbsp; &nbsp; &nbsp; } else if (/^[A-Z][a-zA-Z0-9]*$/.test(text)) {
&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; // 大驼峰命或全大写
&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; // return text.replace(/([A-Z])/g, ' $1').trim().toLowerCase();
&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; return text.replace(/([a-z0-9])([A-Z])/g, "$1 $2").toLowerCase();
&nbsp; &nbsp; &nbsp; &nbsp; } else if (/^[a-zA-Z][a-zA-Z0-9_]*$/.test(text)) {








完美世界
***@***.***



&nbsp;
