### ISSUE TITLE
无法打开扩展设置

### ISSUE THREAD

**Issue by luhongweiyu** [pcloth/translate-speaker#3]
大佬你好.我安装了您的插件后.没法打开您这插件的扩展设置!而且也不能打开其他扩展的设置.只有禁用您这插件后才能打开其他扩展的设置

**Comment by pcloth** [comment]
> 大佬你好.我安装了您的插件后.没法打开您这插件的扩展设置!而且也不能打开其他扩展的设置.只有禁用您这插件后才能打开其他扩展的设置

你把vscode升级到1.61试试，似乎是最近1.60的某个bug冲突造成。
