### ISSUE TITLE
请教问题 results.forEach is not a function

### ISSUE THREAD

**Issue by tjt740** [pcloth/translate-speaker#7]
2022年11月21日，我先后用了不同的电脑 mac+ windows 都尝试过了 无法翻译，一直报 results.forEach is not a function 这个问题，大佬有何解决办法呢？ 以前用的百度id密钥能用的，就突然这段时间不行了。  求教，万分感激

**Comment by pcloth** [comment]
> 2022年11月21日，我先后用了不同的电脑 mac+ windows 都尝试过了 无法翻译，一直报 results.forEach is not a function 这个问题，大佬有何解决办法呢？ 以前用的百度id密钥能用的，就突然这段时间不行了。 求教，万分感激

应该就是你的密钥出问题了，无法获得正确的结果。
