### ISSUE TITLE
提个优化建议

### ISSUE THREAD

**Issue by tjt740** [pcloth/translate-speaker#9]
<img width="697" alt="image" src="https://github.com/pcloth/translate-speaker/assets/59766436/797d59f7-ba68-4f32-9013-4cce9a98649d">

大佬你好，我想提个优化建议。你看是否可以增加个格式化文本内容的功能。 如【驼峰翻译助手】这个vscode插件这样，可以格式化文本内容。  如果有这个功能，简直完美🥰

**Comment by pcloth** [comment]
> <img alt="image" width="697" src="https://user-images.githubusercontent.com/59766436/247900792-797d59f7-ba68-4f32-9013-4cce9a98649d.png">
> 大佬你好，我想提个优化建议。你看是否可以增加个格式化文本内容的功能。 如【驼峰翻译助手】这个vscode插件这样，可以格式化文本内容。 如果有这个功能，简直完美🥰

已经与1.5.1版本提供了相似的功能，请看一下codingFormat参数，用来配置格式和顺序

![1692792780901](https://github.com/pcloth/translate-speaker/assets/18551791/79b86121-9132-4048-b423-e79b82044288)

**Comment by pcloth** [comment]
> <img alt="image" width="697" src="https://user-images.githubusercontent.com/59766436/247900792-797d59f7-ba68-4f32-9013-4cce9a98649d.png">
> 大佬你好，我想提个优化建议。你看是否可以增加个格式化文本内容的功能。 如【驼峰翻译助手】这个vscode插件这样，可以格式化文本内容。 如果有这个功能，简直完美🥰

已经于1.5.1版本提供了这个功能，详情见codingFormat参数
